module tecgraf {
module openbus {
module demo {
module transformations {

	typedef string TransformationId;
	typedef sequence<TransformationId> TransformationIdSeq;
	typedef sequence<double> Transformation;

	exception UnknownTransformation { TransformationId id; };

	interface TransformationRepository {
		TransformationIdSeq listTransformations();$\exlabel{listtypes}$
		Transformation getTransformation(in TransformationId id)$\exlabel{getdata}$
			raises (UnknownTransformation);
	};

};
};
};
};
